collections:
  - name: "vesti"
    label: "Vesti"
    folder: "src/content/vesti"
    create: true
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "tekst", name: "body", widget: "markdown", i18n: true }

  - name: "akcije"
    label: "Akcije"
    folder: "src/content/akcije"
    create: true
    i18n: true
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "tekst", name: "body", widget: "markdown", i18n: true }

media_folder: "/src/assets/images/"
public_folder: "@assets/images/"

site_url: https://blokade.org
logo_url: https://blokade.org/favicon.ico

locale: en

i18n:
  structure: multiple_folders
  locales: [sr, en]
  default_locale: sr

backend:
  name: github
  repo: blokada-rs/sajt
  branch: main
