site_url: https://blokade.org
logo_url: https://blokade.org/favicon.ico

media_folder: "/src/assets/images/"
public_folder: "@assets/images/"

locale: sr

backend:
  name: github
  repo: blokada-rs/sajt
  branch: to-publish

i18n:
  structure: multiple_folders
  locales: [sr, en]
  default_locale: sr
  save_all_locales: false

collections:
  - name: "stranice"
    label: "Stranice"
    i18n:
      structure: single_file
    files:
      - label: "Početna"
        name: "pocetna"
        file: "src/content/stranice/početna.md"
        create: false
        i18n: true
        fields:
          - { label: "Naslov", name: "naslov", widget: "string", i18n: true }
          - { label: "Opis", name: "opis", widget: "markdown", i18n: true }
          - { label: "Zahtevi", name: "zahtevi", widget: "markdown", i18n: true }

      - label: "O Blokadama"
        name: "o-blokadama"
        file: "src/content/stranice/o-blokadama.md"
        create: false
        i18n: true
        fields:
          - { label: "Tekst", name: "tekst", widget: "markdown", i18n: true }

      - label: "Zaglavlje"
        name: "zaglavlje"
        file: "src/content/stranice/zaglavlje.md"
        create: false
        i18n: true
        fields:
          - label: "Naslov"
            name: "naslov"
            widget: "string"
            i18n: true

          - label: "Linkovi"
            name: "linkovi"
            widget: "list"
            i18n: true
            fields:
              - { label: "Naslov", name: "naziv", widget: "string", i18n: true }
              - { label: "Link", name: "link", widget: "string", i18n: true }

  - name: "vesti"
    label: "Vesti"
    folder: "src/content/vesti"
    create: true
    i18n: true
    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true, optional: true }

  - name: "akcije"
    label: "Akcije"
    folder: "src/content/akcije"
    create: true
    i18n: true

    sortable_fields:
      fields: [pubDate]
      default:
        field: pubDate
        direction: descending
    fields:
      - { label: "Naslov", name: "title", widget: "string", i18n: true }
      - { label: "Draft", name: "draft", widget: "boolean", i18n: true }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime", i18n: "duplicate" }
      - { label: "Glavna slika", name: "heroImage", widget: "image", i18n: "duplicate" }
      - { label: "Tekst", name: "body", widget: "markdown", i18n: true, optional: true }
