collections:
  - name: "vesti"
    label: "Vesti"
    folder: "src/content/vesti"
    create: true
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime" }
      - { label: "Glavna slika", name: "heroImage", widget: "image" }
      - { label: "tekst", name: "body", widget: "markdown" }

  - name: "akcije"
    label: "Akcije"
    folder: "src/content/akcije"
    create: true
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum objavljivanja", name: "pubDate", widget: "datetime" }
      - { label: "Glavna slika", name: "heroImage", widget: "image" }
      - { label: "tekst", name: "body", widget: "markdown" }

  - name: "donacije"
    label: "Namirnice za donacije"
    folder: "src/content/donacije"
    create: false
    identifier_field: fakultet
    fields:
      -  name: "fakultet"
         widget: "hidden"
      - label: "namirnice"
        name: "namirnice"
        label_singular: "namirnica"
        widget: "list"
        fields:
          - label: "Naziv"
            name: "naziv"
            widget: "string"
          - label: "Dodatni opis"
            name: "opis"
            widget: "text"
          - label: "Prioritet"
            name: "prioritet"
            widget: "select"
            options: [ "visok", "srednji", "nizak" ]

media_folder: "/src/assets/images/" # Location where files will be stored in the repo
public_folder: "/src/assets/images/" # The src attribute for uploaded media
locale: hr

backend:
  name: github
  repo: blokada-rs/sajt
  branch: main
